// GENERATED FILE - DO NOT EDIT
// ------------------------------------------------------------
// This file was generated by the FlutterFire CLI.
// ------------------------------------------------------------

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW-Icwz5ber6XMSqTpSgwPtVJ4odBAi04',
    appId: '1:190038211652:android:f079f15f4a12a6edf65011',
    messagingSenderId: '190038211652',
    projectId: 'komai-food',
    storageBucket: 'komai-food.firebasestorage.app',
  );

  /// 🔹 Android

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrd_W2-I11f950Mv1EEA28vNlbFZxo6oE',
    appId: '1:190038211652:web:62fa4ff307a49048f65011',
    messagingSenderId: '190038211652',
    projectId: 'komai-food',
    authDomain: 'komai-food.firebaseapp.com',
    storageBucket: 'komai-food.firebasestorage.app',
    measurementId: 'G-06ZR8X76G8',
  );

  /// 🔹 Web (ถ้าไม่ได้ใช้ Web สามารถปล่อยไว้ได้)

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPODMc74Azm5tC_6wRNm-qUsg9fi0lM_E',
    appId: '1:190038211652:ios:cfb6203564c22b23f65011',
    messagingSenderId: '190038211652',
    projectId: 'komai-food',
    storageBucket: 'komai-food.firebasestorage.app',
    iosBundleId: 'com.example.komaiFood',
  );

  /// 🔹 iOS (ใส่เมื่อใช้จริง)

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPODMc74Azm5tC_6wRNm-qUsg9fi0lM_E',
    appId: '1:190038211652:ios:cfb6203564c22b23f65011',
    messagingSenderId: '190038211652',
    projectId: 'komai-food',
    storageBucket: 'komai-food.firebasestorage.app',
    iosBundleId: 'com.example.komaiFood',
  );

  /// 🔹 macOS (ถ้าไม่ใช้ ปล่อยไว้)

  /// 🔹 Windows (ถ้าไม่ใช้ ปล่อยไว้)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyXXXXXXXXXXXXXXX",
    appId: "1:755264578542:windows:xxxxxxxxxxxxxxxx",
    messagingSenderId: "755264578542",
    projectId: "sutee-flutter-demo",
    storageBucket: "sutee-flutter-demo.appspot.com",
  );
}